### Системы линейных уравнений. Часть 1

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

Запишем расширенную матрицу системы, вычтем из второй строки первую, умноженную на 2, вычтем из третьей строки первую:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix} \rightarrow 
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix} \rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$

Оставшаяся матрица соответствует системе, которая имеет бесконечное количество решений:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}&=0, \\
-x_{2}+x_{3}+5x_{4}&=-2, \\
-2x_{3}+3x_{4}&=4.
\end{cases}$$

$$x_{4}=c,$$
$$-2x_{3}+3c=4 \; \Leftrightarrow \; x_{3}=\frac{3c}{2}-2,$$
$$-x_{2}+(\frac{3c}{2}-2)+5c=-2 \; \Leftrightarrow \; x_{2}=\frac{13c}{2},$$
$$x_{1} + \frac{13c}{2} - (\frac{3c}{2}-2) - 2c=0 \; \Leftrightarrow \; x_{1}=-3c-2.$$

Таким образом решение:
$$\begin{cases}
x_{1}=-3c-2, \\
x_{2}=\frac{13c}{2}, \\
x_{3}=\frac{3c}{2}-2, \\
x_{4}=c \in \mathbb{R}.
\end{cases}$$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

а) Запишем расширенную матрицу системы:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1  \\ 
2 & -5 & -3 \\ 
1 & 1 & -1 
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
0
\end{matrix}
\end{pmatrix}$$

$rank \tilde A=rank A=3$. Число неизвестных тоже $=3$. Это означает, что система определена, т. е. имеет единственное решение.

б) Запишем расширенную матрицу системы:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6  \\ 
1 & -2 & 3 \\ 
3 & -6 & 9
\end{matrix}\right|
\begin{matrix}
1\\ 
-2\\
5
\end{matrix}
\end{pmatrix}$$

$rank A=1 < rank \tilde A=3$. Это означает, что система несовместна, т.е. не имеет решений

в) Запишем расширенную матрицу системы:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5  \\ 
3 & 1 & -8 
\end{matrix}\right|
\begin{matrix}
4\\ 
-2
\end{matrix}
\end{pmatrix}$$

$rank A = rank \tilde A = 2$. Число неизвестных $=3$. Это означает, что система имеет бесконечное количество решений.

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

$rank A = rank \tilde A = 4$. Число неизвестных $=4$. Это означает, что система определена, т. е. имеет единственное решение.

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix} \rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c
\end{matrix}
\end{pmatrix} \rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c-7a
\end{matrix}
\end{pmatrix} \rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c+a-2b
\end{matrix}
\end{pmatrix}$$

Для того чтобы система была несовместна, должно выполняться условие:
$c+a-2b = 0$

### Системы линейных уравнений. Часть 2

In [1]:
import numpy as np

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

а) Найдем определитель матрицы коэффициентов:

$$detA=\begin{vmatrix}
1 & -2\\ 
3 & -4
\end{vmatrix}=-4-3\cdot(-2)=2\neq 0,$$

следовательно, система совместна.

Найдем определители $detA_{1}$, $detA_{2}$:

$$detA_{1}=\begin{vmatrix}
1 & -2\\ 
7 & -4
\end{vmatrix}=-4-7\cdot(-2)=10, \quad
detA_{2}=\begin{vmatrix}
1 & 1\\ 
3 & 7
\end{vmatrix}=7-3\cdot1=4$$

Найдем решение по формулам Крамера:

$$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2}=5, \quad
x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2}=2$$

In [2]:
a = np.array([[1,-2],[3,-4]])
b = np.array([[1],[7]])
np.linalg.solve(a,b)

array([[5.],
       [2.]])

б) Найдем определитель матрицы коэффициентов:

$$detA=\begin{vmatrix}
2 & -1 & 5\\ 
1 & 1 & -3\\ 
2 & 4 & 1
\end{vmatrix}=
2\begin{vmatrix}
1 & -3\\ 
4 & 1 
\end{vmatrix}-
(-1)\begin{vmatrix}
1 & -3\\ 
2 & 1 
\end{vmatrix}+
5\begin{vmatrix}
1 & 1 \\ 
2 & 4
\end{vmatrix}=2(1 \cdot 1-4\cdot (-3))+(1\cdot 1-2\cdot (-3))+5(1\cdot 4-2\cdot 1)=43\neq 0,$$

следовательно, система совместна.

Найдем определители $detA_{1}$, $detA_{2}$, $detA_{3}$:

$$detA_{1}=\begin{vmatrix}
10 & -1 & 5\\ 
-2 & 1 & -3\\ 
1 & 4 & 1
\end{vmatrix}=
10\begin{vmatrix}
1 & -3\\ 
4 & 1 
\end{vmatrix}-
(-1)\begin{vmatrix}
-2 & -3\\ 
1 & 1 
\end{vmatrix}+
5\begin{vmatrix}
-2 & 1 \\ 
1 & 4
\end{vmatrix}=10(1 \cdot 1-4\cdot (-3))+(-2\cdot 1-1\cdot (-3))+5(-2\cdot 4-1\cdot 1)=86$$

$$detA_{2}=\begin{vmatrix}
2 & 10 & 5\\ 
1 & -2 & -3\\ 
2 & 1 & 1
\end{vmatrix}=
2\begin{vmatrix}
-2 & -3\\ 
1 & 1 
\end{vmatrix}-
10\begin{vmatrix}
1 & -3\\ 
2 & 1 
\end{vmatrix}+
5\begin{vmatrix}
1 & -2 \\ 
2 & 1
\end{vmatrix}=2(-2 \cdot 1-1\cdot (-3))-10(1\cdot 1-2\cdot (-3))+5(1\cdot 1-2\cdot (-2))=-43$$

$$detA_{3}=\begin{vmatrix}
2 & -1 & 10\\ 
1 & 1 & -2\\ 
2 & 4 & 1
\end{vmatrix}=
2\begin{vmatrix}
1 & -2\\ 
4 & 1 
\end{vmatrix}-
(-1)\begin{vmatrix}
1 & -2\\ 
2 & 1
\end{vmatrix}+
10\begin{vmatrix}
1 & 1 \\ 
2 & 4
\end{vmatrix}=2(1 \cdot 1-4\cdot (-2))+(1\cdot 1-2\cdot (-2))+10(1\cdot 4-2\cdot 1)=43$$

Найдем решение по формулам Крамера:

$$x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43}=2, \quad x_{2} = \frac{detA_{2}}{detA} = \frac{-43}{43}=-1, \quad x_{3} = \frac{detA_{3}}{detA} = \frac{43}{43}=1$$

In [3]:
a = np.array([[2,-1,5],[1,1,-3],[2,4,1]])
b = np.array([[10],[-2],[1]])
np.linalg.solve(a,b)

array([[ 2.],
       [-1.],
       [ 1.]])

__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

а) $\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix} \rightarrow
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix} \rightarrow
U=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$

Матрица $L$ при этом имеет вид: 
$\quad\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$

б) $\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix} \rightarrow
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix} \rightarrow
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix} \rightarrow
U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$

Матрица $L$ при этом имеет вид: 
$\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}$

__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

$A = \begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix} \rightarrow
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1.5 & -11.5 \\ 
0 & 3.5 & -9.5
\end{pmatrix} \rightarrow
U=\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1.5 & -11.5 \\ 
0 & 0 & \frac{52}{3}
\end{pmatrix},\quad L=\begin{pmatrix}
1 & 0 & 0 \\ 
5.5 & 1 & 0 \\ 
4.5 & \frac{7}{3} & 1
\end{pmatrix}$

Решим теперь систему $Ly=b:$

$$\begin{cases}
y_{1}=1, \\
5.5y_{1}+y_{2}=-6, \\
4.5y_{1}+\frac{7}{3}y_{2}+y_{3}=-5
\end{cases}\rightarrow
\begin{cases}
y_{1}=1, \\
y_{2}=-11.5, \\
y_{3}=\frac{52}{3}
\end{cases}$$

И затем систему $Ux=y:$

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1, \\
1.5x_{2}-11.5x_{3}=-11.5, \\
\frac{52}{3}x_{3}=\frac{52}{3}
\end{cases}\rightarrow
\begin{cases}
x_{1}=-1, \\
x_{2}=0, \\
x_{3}=1
\end{cases}$$

In [4]:
a = np.array([[2,1,3],[11,7,5],[9,8,4]])
b = np.array([[1],[-6],[-5]])
np.linalg.solve(a,b)

array([[-1.00000000e+00],
       [ 2.44249065e-16],
       [ 1.00000000e+00]])

__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

Произведем разложение на $LL^{T}$:

$$l_{11}=\sqrt{a_{11}}=9, \quad l_{21}=\frac{a_{21}}{l_{11}}=-5, \quad l_{31}=\frac{a_{31}}{l_{11}}=5,$$

$$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=5,$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5}\left (-15-(-5)\cdot5 \right )=2,$$
$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-5^2-2^2}=3.$$


Получили матрицу 

$$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$$

Решим систему $Ly=b:$

$$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases} \rightarrow
\begin{cases}
y_{1}=59, \\
y_{2}=-33, \\
y_{3}=-12.
\end{cases}$$

И решим систему $L^{T}x=y:$

$$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59, \\
5x_{2}+2x_{3}=-33, \\
3x_{3}=-12.
\end{cases} \rightarrow
\begin{cases}
x_{1}=6, \\
x_{2}=-5, \\
x_{3}=-4.
\end{cases}$$

In [5]:
a = np.array([[81,-45,45],[-45,50,-15],[45,-15,38]])
b = np.array([[531],[-460],[193]])
np.linalg.solve(a,b)

array([[ 6.],
       [-5.],
       [-4.]])

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.