### Матрицы и матричные операции. Часть 1

In [1]:
import numpy as np

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

а) ни AB, ни BA произведение не определено

б) AB - размерность полученной матрицы 2х3, BA - не определено

в) AB - размерность полученной матрицы 8х8, BA - размерность полученной матрицы 3х3

г) AB и BA - размерность полученной матрицы 4х4

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A+B=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}+\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}=\begin{pmatrix}
1+4 & -2+(-1)\\ 
3+0 & 0+5
\end{pmatrix}=\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

$A\cdot B=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \cdot \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}=\begin{pmatrix}
1\cdot4+(-2)\cdot0 & 1\cdot(-1)+(-2)\cdot5\\ 
3\cdot4+0\cdot0 & 3\cdot(-1)+0\cdot5
\end{pmatrix}=\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

In [2]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
print(a+b)
print(np.dot(a,b))

[[ 5 -3]
 [ 3  5]]
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A-2B+4C=3\cdot\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} -2\cdot \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}+4\cdot\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}=\begin{pmatrix}
3-0+8 & 21-10-16\\ 
9-4+4 & -18+2+4
\end{pmatrix}=\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [3]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])
print(3*a-2*b+4*c)

[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A^{T} = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$

$AA^{T}=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}\cdot\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}=\begin{pmatrix}
4\cdot4+1\cdot1 & 4\cdot5+1\cdot(-2) & 4\cdot2+1\cdot3\\ 
5\cdot4+(-2)\cdot1 & 5\cdot5+(-2)\cdot(-2) & 5\cdot2+(-2)\cdot3\\
2\cdot4+3\cdot1 & 2\cdot5+3\cdot(-2) & 2\cdot2+3\cdot3
\end{pmatrix}=\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\
11 & 4 & 13
\end{pmatrix}$

$A^{T}A=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}\cdot\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}=\begin{pmatrix}
4\cdot4+5\cdot5+2\cdot2 & 4\cdot1+5\cdot(-2)+2\cdot3\\ 
1\cdot4+(-2)\cdot5+3\cdot2 & 1\cdot1+(-2)\cdot(-2)+3\cdot3\\
\end{pmatrix}=\begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}$

In [4]:
a = np.array([[4, 1], [5, -2], [2, 3]])

print(np.dot(a,a.T))
print(np.dot(a.T,a))

[[17 18 11]
 [18 29  4]
 [11  4 13]]
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [5]:
def dot(a,b):
    c = [[0 for i in range(len(b[0]))] for j in range(len(a))] # результирующая матрица
    if len(b) != len(a[0]):
        return('Произведение не определено')
    else:
        for i in range(len(a)):
            for j in range(len(b[0])):  
                c[i][j] = sum(a[i][k] * b[k][j] for k in range(len(b)))
    return c

In [6]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
print(dot(a,b))

[[4, -11], [12, -3]]


In [7]:
a = np.array([[1, -2, 3], [3, 0, 2]])
b = np.array([[4, -1], [0, 5]])
print(dot(a,b))

Произведение не определено


### Матрицы и матричные операции. Часть 2

__1.__ Вычислить определитель (используйте любой удобный для вас способ вычисления определителя: через миноры, через перестановки или другой):

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

а) $det = sinx\cdot sinx - cosx\cdot(-xcosx) = sin^2{x}+cos^2{x}=1$

б) $det = 0 - 0 + 9\cdot\begin{vmatrix}
4 & 2\\ 
0 & 5
\end{vmatrix}=9\cdot4\cdot5-9\cdot0\cdot2=180$

в) $det = 1\cdot\begin{vmatrix}
5 & 6\\ 
8 & 9
\end{vmatrix}-2\cdot\begin{vmatrix}
4 & 6\\ 
7 & 9
\end{vmatrix}+3\cdot\begin{vmatrix}
4 & 5\\ 
7 & 8
\end{vmatrix}= 1\cdot(45-48)-2\cdot(36-42)+3\cdot(32-35)=-3+12-9=0$

In [8]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'{np.linalg.det(a):.0f}')
print(f'{np.linalg.det(b):.0f}')

180
-0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

$ det(A)=4$

а) $det(A^2)=det(A)\cdot det(A)=16$

б) $det(A^{T})=det(A)=4$

в) $det(2A)=2^n det(A)=2^n\cdot4=2^{n+2}$, где n - порядок матрицы А

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

$det = (-2)\cdot((-14)\cdot13-7\cdot6)-7\cdot(4\cdot13-6\cdot(-3))-3\cdot(4\cdot7-(-14)\cdot(-3))=448-490+42=0$

определитель матрицы равен нулю, следовательно матрица - вырожденная

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

а) третья строка является суммой первых двух, отбросим ее

ранг матрицы = 2

б) третья строка является суммой первых двух, отбросим ее

ранг матрицы = 3

In [9]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(np.linalg.matrix_rank(a))
print(np.linalg.matrix_rank(b))

2
3
